### PR TITLE
Node and cover are 3D now

### LINKED ISSUE #487: error new vw_wastewater_node and vw_cover
Wanted to add a new wastewater_node in layer vw_wastewater_node (add point feature): got this error:
Layer vw_wastewater_node: PostGIS error while adding features: FEHLER: Column has Z dimension but geometry does not

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #487

### CODE REVIEW

**Comment by m-kuhn** [comment]
@urskaufmann can you try this file https://github.com/QGEP/QGEP/raw/db37b9532d0c8c5f7dd97ebb3d7a071a4401dc39/project/qgep_en.qgs

**Comment by urskaufmann** [comment]
Works!

**Comment by varrieta** [comment]
@m-kuhn I get the same issue with our projet. Should I change something special in it?

**Comment by m-kuhn** [comment]
It's probably easiest to edit the XML directly https://github.com/QGEP/QGEP/commit/db37b9532d0c8c5f7dd97ebb3d7a071a4401dc39

**Pull request merged**
