### PR TITLE
update views for datamodel 1.3.0

### PR DESCRIPTION
**Pull request by 3nids**
depends on https://github.com/QGEP/datamodel/pull/95/

### CODE REVIEW

**Comment by lbartoletti** [comment]
I tested with a demo data (updated from #95) but I have a problem with 4 tables and can't use the plugin (not enabled)

image

**Comment by lbartoletti** [comment]
OK for vw_network_segment you have to refresh the materialized view as mentionned https://github.com/QGEP/QGEP/issues/334

**Comment by 3nids** [comment]
did you use the updated model? it looks like you're still on an old one.

**Comment by 3nids** [comment]
I will try to add the refresh views to a post-all.py so you should be good with this one

**Comment by lbartoletti** [comment]
LGTM. Thanks.

**Pull request merged**
