### PR TITLE
allow to specify wasterwater node geometry in the manhole/cover wizard

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by m-kuhn** [comment]
What is the workflow to digitize different CO and WN geometries?
The plan so far was:

 1. Use the "pickellochmodell" for every new entry
 2. Manually move the WN where required in a later step

**Comment by 3nids** [comment]
I use the view in FME.
I think it's the best way, since you can't order the elements in FME (be sure to create the special structure before the node). Therefore, it would require duplicating the script for each sub-class.

**Comment by 3nids** [comment]
using COALESCE allows to keep the current workflow and to work for me in FME.

**Comment by m-kuhn** [comment]
I see,
Ok for me

**Pull request merged**
