### PR TITLE
Maintenance/WS link table: Remove surrogate key

### PR DESCRIPTION
**Pull request by m-kuhn**
Proposal to stick to database "standards" for link tables.
Instead of a surrogate primary key a compound key could be used.

See http://stackoverflow.com/a/2190294/2319028

References #113

### CODE REVIEW

**Comment by 3nids** [comment]
this misses indexes on the fk_* columns (they are not created automatically on foreign keys).
Not sure in case of a compound key, if the index on the two columns is enough. I would tend to also add the two indexes on the columns.

**Comment by m-kuhn** [comment]
I guess they also need to be created for each column on its own for
compound keys, afaik there is only an index containing a combination of
both created.

**Comment by 3nids** [comment]
@sjib will it be part of next release?

**Comment by m-kuhn** [comment]
Should be ok already, no?
https://github.com/QGEP/datamodel/blob/master/11_n_m_relations.sql

**Comment by 3nids** [comment]
yep, sorry.

**Pull request closed without merging**
