### PR TITLE
Add relation from and to wastewater_structure in reach

### PR DESCRIPTION
**Pull request by lbartoletti**
This PR adds a relation to navigate from reach to wastewater_structure from and to with the widget form "relations reference"

image
cc @ponceta

### CODE REVIEW

**Comment by m-kuhn** [comment]
To the channel which is defined on the reach?

**Comment by lbartoletti** [comment]
Reach points on vw_qgep_reach

**Comment by sjib** [comment]
Can you explain the motivation behind this? This does not influence the datamodel?

**Comment by lbartoletti** [comment]
The motivation is to show which chamber are from and to the reach.

ping @ponceta

**Comment by sjib** [comment]
So I can see the list in the pull down? Do you show the identifier?

**Comment by ponceta** [comment]
The goal is to assess that topology is well defined and that it enables navigation between entities :

Related to :
https://github.com/QGEP/QGEP/issues/363

**Pull request closed without merging**
