### PR TITLE
improved Makefile

### PR DESCRIPTION
**Pull request by 3nids**
I used a Makefile I use in my plugins.
It's a bit more complete.

changes:
* it uses resources_rc.py hence ui files can make use of resources from the main file (pyuic will look for resources_rc.py and resources.py)
* ui files are preceeded by "ui_", it was like this in the Makefile, no special reason, can revert if wanted
* it automates deploy, zip and publish (will need adjustment).
* removes compiled ui files (no need to be on git, right?)

### CODE REVIEW

**Comment by m-kuhn** [comment]
* +1 for the _rc change,
 * +0 for the _ui change
 * For zip and publish I used the script here https://github.com/qgep/QGEP/blob/master/qgepplugin/scripts/make-qgep-release.sh That does some background work like tagging the git repo.
 * What's up with the 3 .py files  in `qgepplugin/ui` ?

**Comment by 3nids** [comment]
oops, restored the files.

what about moving the release script in the makefile?
otherwise, I can remove the publish/release.
But there is now some redundancy for the translations.

What do you prefer?

**Comment by m-kuhn** [comment]
How is the version number specified for the Makefile?

**Comment by 3nids** [comment]
it's read from metadata
https://github.com/qgep/QGEP/commit/9cca5a1a86f0322eba68f8fe2d580412c736f792#diff-55b7e7952eacd11e2d5148dfa1fad225R34

**Comment by m-kuhn** [comment]
We could move some logic to the Makefile and have the release-script call the Makefile.

Concerning the compiled .ui files... My understanding is, that the .ui files should be on git while the generated .py file should be in `.gitignore`. If we remove the .ui files it is quite hard to adjust them later on.

**Pull request closed without merging**
