### PR TITLE
Add a refresh network topology button

### PR DESCRIPTION
**Pull request by tudorbarascu**
Fixes https://github.com/QGEP/QGEP/issues/127

When clicking the button, the network materialized views get refreshed.
The user also gets notified through the message bar if everything worked out allright.

Done by Cătălin Proteasa and Tudor Bărăscu

### CODE REVIEW

**Comment by m-kuhn** [comment]
Cool!

**Comment by tudorbarascu** [comment]
Rebased with the fixed typos. We were also thinking of doing some work on the database connection part. Should we also take into consideration the possibility that the connection won't be done with pg_service but with normal connection?

**Comment by m-kuhn** [comment]
Does this change a lot?
For me it is fine to make the pg_service standard. I am even considering adding an assistant to the plugin that autocreates the pg_service entries when you create a new project.

**Comment by m-kuhn** [comment]
What do you think: after recreating the materialized views the networkx graph should be cleaned and recreated

**Comment by tudorbarascu** [comment]
Yes, it's clear that the graph should be cleaned and recreated.
Will do it. (+ fixing the last typo hopefully ; )  Thanks for assisting.

**Comment by m-kuhn** [comment]
Thanks for participating, glad to have your support!

**Comment by tudorbarascu** [comment]
Thanks for the hints! It works really nice for me..

**Comment by tudorbarascu** [comment]
Done

**Comment by m-kuhn** [comment]
Is this ready?

**Comment by tudorbarascu** [comment]
Hi, It is ready to merge as from the user point of view it works at it should.
I tried moving the clearing part in the creategraph but it didn't work as it should.
As I'm on vacation I don't have the time to investigate thoroughly.

**Pull request merged**
